AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless PR Police
Resources:
  GetPRInfo:
    Type: AWS::Serverless::Function
    Properties:
      Role: !Ref BotIAM
      CodeUri: ./build/
      Handler: index.index
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Timeout: 300
      MemorySize: 128
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /index
            Method: post
      Environment:
        Variables:
          SlackToken: !Ref SlackToken
          NodeEnv: !Ref NodeEnv
          Token: !Ref Token
          TABLE_NAME: !Ref User
  User:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Parameters:
  BotIAM:
    Default: ""
    Type: String
  SlackToken:
    Default: ""
    Type: String
  NodeEnv:
    Default: "test"
    Type: String
  Token:
    Default: ""
    Type: String
