AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless PR Police
Resources:
  User:
    Type: AWS::Serverless::SimpleTable

  GetPRInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/
      Handler: index.index
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Timeout: 300
      MemorySize: 128
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /index
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref User
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          NODE_ENV: !Ref NodeEnv
          Token: !Ref Token
          TableName: !Ref User
Parameters:
  BotIAM:
    Default: ""
    Type: String
  SlackToken:
    Default: ""
    Type: String
  NodeEnv:
    Default: "test"
    Type: String
  Token:
    Default: ""
    Type: String
